version: '3.8'

services:
  mongo:
    container_name: mongo
    build:
      dockerfile: ./docker/mongo.Dockerfile
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: prisma
      MONGO_REPLICA_HOST: 127.0.0.1
      MONGO_REPLICA_PORT: 27018
    env_file:
      - .env.staging
    ports:
      - '27018:27018'

  redis:
    container_name: cache
    image: redis
    ports:
      - 6379:6379

  api:
    build:
      dockerfile: ./docker/api.Dockerfile
    environment:
      DATABASE_URL: mongodb://root:prisma@mongo:27018/prisma-mongo?authSource=admin&replicaSet=rs0&retryWrites=true&w=majority&directConnection=true
    env_file:
      - .env.staging
    ports:
      - '3000:3000'
    depends_on:
      - mongo